const SET_CURRENT_USER = "SET_CURRENT_USER"
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
const BEGIN_AUTH = "BEGIN_AUTH"
const COMPLETE_AUTH = "COMPLETE_AUTH"
const ADD_EXPENSE = "ADD_EXPENSE"
const DELETE_EXPENSE = "DELETE_EXPENSE"
const GET_EXPENSE = "GET_EXPENSE"
const ADD_INCOME = "ADD_INCOME"
const DELETE_INCOME = "DELETE_INCOME"
const ADD_FARM = "ADD_FARM"
const DELETE_FARM = "DELETE_FARM"


export{
    SET_CURRENT_USER,
    CLEAR_CURRENT_USER,
    BEGIN_AUTH,
    COMPLETE_AUTH,
    ADD_EXPENSE,
    DELETE_EXPENSE,
    GET_EXPENSE,
    ADD_INCOME,
    DELETE_INCOME,
    ADD_FARM,
    DELETE_FARM,
}