const SET_CURRENT_USER = "SET_CURRENT_USER"
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
const BEGIN_AUTH = "BEGIN_AUTH"
const COMPLETE_AUTH = "COMPLETE_AUTH"
const ADD_EXPENSE = "ADD_EXPENSE"
const DELETE_EXPENSE = "DELETE_EXPENSE"
const GET_EXPENSE = "GET_EXPENSE"
const ADD_INCOME = "ADD_INCOME"
const DELETE_INCOME = "DELETE_INCOME"

export{
    SET_CURRENT_USER,
    CLEAR_CURRENT_USER,
    BEGIN_AUTH,
    COMPLETE_AUTH,
    ADD_EXPENSE,
    DELETE_EXPENSE,
    GET_EXPENSE,
    ADD_INCOME,
    DELETE_INCOME
}