const SET_CURRENT_USER = "SET_CURRENT_USER"
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
const BEGIN_AUTH = "BEGIN_AUTH"
const COMPLETE_AUTH = "COMPLETE_AUTH"
const ADD_FARM = "ADD_FARM"
const DELETE_FARM = "DELETE_FARM"
const GET_FARMS = "GET_FARMS"
const SET_FARM = "SET_FARM"
const UNSET_FARM = "UNSET_FARM"
const ADD_CROP = "ADD_CROP"
const DELETE_CROP = "DELETE_CROP"
const GET_CROPS = "GET_CROPS"
const SET_CROP = "SET_CROP"
const UNSET_CROP = "UNSET_CROP"
const ADD_INCOME = "ADD_INCOME"
const DELETE_INCOME = "DELETE_INCOME"
const GET_INCOMES = "GET_INCOMES"
const ADD_EXPENSE = "ADD_EXPENSE"
const DELETE_EXPENSE = "DELETE_EXPENSE"
const GET_EXPENSES = "GET_EXPENSES"



export{
    SET_CURRENT_USER,
    CLEAR_CURRENT_USER,
    BEGIN_AUTH,
    COMPLETE_AUTH,
    ADD_FARM,
    DELETE_FARM,
    GET_FARMS,
    SET_FARM,
    UNSET_FARM,
    ADD_CROP,
    DELETE_CROP,
    GET_CROPS,
    SET_CROP,
    UNSET_CROP,
    ADD_INCOME,
    DELETE_INCOME,
    GET_INCOMES,
    ADD_EXPENSE,
    DELETE_EXPENSE,
    GET_EXPENSES,

}